### ISSUE TITLE
Broken and incosistent keyboard shortcuts

### ISSUE THREAD

**Issue by RadekCap** [thinkingrock-gtd/tr-pc#103]
In the latest version default shortcut for "Collect thoughts isn't working" (Ctrl+Shift+1) from some screens. I haven't found a pattern here.

Overview (Ctrl+Shift+O) - on the toolbar is displayed as Overview but it's opening "Open Project" dialog.

Linux. Application is running from Netbeans IDE.

**Comment by ursjoss** [comment]
Maybe aregression introduced by reverting #57 in PR #100.

**Comment by RadekCap** [comment]
@ursjoss very good guess!

Yes, it was introduced by f89eab3a664513300b12baa81410510c48f1fa70 commit.

**Comment by RadekCap** [comment]
And, the same commit reintroduced #64.

**Comment by ursjoss** [comment]
@RadekCap That was kinda expected. We'll need to find another way of resolving those without failing the build.

**Comment by RadekCap** [comment]
If I remember it well, Find in Project shortcut should be disabled. Currently is enabled as well.

![Screenshot from 2023-03-01 10-20-27](https://user-images.githubusercontent.com/6508800/222096858-dc357e24-fb04-4027-8cdf-d746d2c41167.png)

**Comment by ursjoss** [comment]
@RadekCap Do you still see that shortcut? I couldn't find it, but don't know where it was...

**Comment by RadekCap** [comment]
No, I tried to close it from recent PR comment but obviously it didn't work. Closing now.
