### ISSUE TITLE
Consider to write script for cache removal

### ISSUE THREAD

**Issue by RadekCap** [thinkingrock-gtd/tr-pc#120]
Having a script removing all caches from the previous installations is very handy for development but it could be useful for users as well. Maybe as a part of the installation, maybe as a part of some cleanup/debugging scripts.

**Comment by ursjoss** [comment]
I suggest adding it as a recipe to the justfile

**Comment by ursjoss** [comment]
The current setup and distinction between "cachedir" and "userdir" is described in #77.

The actual paths used for a particular running TR instance can be seen in the About dialog - here from an installed version of TR on linux:
![image](https://user-images.githubusercontent.com/357238/224371633-6091a6fc-c212-43cf-b232-ea3c786aeb6b.png)

And here for a version started from Netbeans on linux:
![image](https://user-images.githubusercontent.com/357238/224372081-b3f6ec59-d2ee-4b28-894d-421d1696e5f5.png)

Deleting recursively is always a risky thing. I suggest we only create a script to delete the cache dir but not the user dir, as it contains logs etc.

**Comment by RadekCap** [comment]
We do not have recursively delete them, just move them from the paths used by an application. And now, it could be very complicated how to deal with it.

I'm still not decided if this is only development issue. Maybe yes.

The idea below this issue is that we should be able to eliminate the previous installation relicts.

**Comment by ursjoss** [comment]
I wouldn't bother about moving them away. They files are just recreated with the next lauch.

**Comment by RadekCap** [comment]
The documentation seems to be sufficient for me.
