### ISSUE TITLE
Lost info about the last opened file?

### ISSUE THREAD

**Issue by RadekCap** [thinkingrock-gtd/tr-pc#124]
@ursjoss this is more a question than an issue now.

I have found, that my TR "is forgetting" the last opened file. The truth is, that practically daily there is a new build so I have fresh binaries. But information about the last opened file was persistent throughout this.

Now, I mention, that TR lost this info - some config? And, in the last opened files there were "foo" and "bar".

I'm going to watch it, it looks like the result of recent changes to me.

**Comment by ursjoss** [comment]
Is that "lost after installation" or "lost after closing TR and re-opening"?

**Comment by RadekCap** [comment]
"Lost after installation" and it means unpacking the zip file from the dist folder.

**Comment by ursjoss** [comment]
I don't see this issue. Could it be related to cache clearing tests?

**Comment by RadekCap** [comment]
It could be.

The issue appeared on both of my systems and I do not have installed just on Linux yet.

I'll watch and I'll test it.

**Comment by ursjoss** [comment]
On my system, the path is stored in the following path:

`~/.java/.userPrefs/ThinkingRock/_!$:!.g!1!#4!:@==/xstream/pref.xml`

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE map SYSTEM "http://java.sun.com/dtd/preferences.dtd">
<map MAP_XML_VERSION="1.0">
  <entry key="data.file" value="/home/urs/tr/gtd.trx"/>
</map>
```

When I re-install the application, my TR instance does  not lose the path of the last opened file.

**Comment by ursjoss** [comment]
@RadekCap I have never experienced this since. I will move this into backlog. If you still suffer from this, please move back to next column.

**Comment by RadekCap** [comment]
I'm closing it as it is not present now.
