### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by ursjoss** [thinkingrock-gtd/tr-pc#129]
test issue to verify if new github action workflow works successfully. It is supposed to automatically add the project [TR Current ](https://github.com/thinkingrock-gtd/tr-pc/projects?query=is%3Aopen)to the issue.

**Comment by RadekCap** [comment]
It seems to be working :)

**Comment by ursjoss** [comment]
Nope, unfortunately not. I did not have time to further dig into it, but the github action doesn't find the github-token. I may solve it or revert the whole approach for now....
