### ISSUE TITLE
Options reveals screens previously hidden

### ISSUE THREAD

**Issue by RadekCap** [thinkingrock-gtd/tr-pc#31]
Options dialog has a few screens previously hidden:

- Editor
- Fonts & Colors
- Team

The latest release version status:
![Screenshot from 2022-12-22 13-26-27](https://user-images.githubusercontent.com/6508800/209135213-80c71ea8-dcca-4165-81f4-254a10cc7774.png)

The current latest status:

![Screenshot from 2022-12-22 13-32-55](https://user-images.githubusercontent.com/6508800/209135287-d3a6b042-b830-48d9-a2b8-82a0c4f77af3.png)

They should be hidden.

**Comment by ursjoss** [comment]
Thanks. Agree, we should hide the following:
- Editor
- Fonts & Colors
- Team
