### ISSUE TITLE
Remove ant-contrib && update documentation

### ISSUE THREAD

**Issue by RadekCap** [thinkingrock-gtd/tr-pc#39]
Remove ant-contrib and JRE installation on mac based on #35 

Update documentation #23

**Comment by RadekCap** [comment]
@ursjoss , pls remove this paragraph

To use ant with ThiningRock, I also had to [download](https://sourceforge.net/projects/ant-contrib/files/ant-contrib/ant-contrib-0.6/ant-contrib-0.6-bin.zip/download) ant-contrib-0.6-bin.zip, unzip it and copy lib/ant-contrib-0.6.jar into the place where ant would find it (in my case on linux into /usr/share/java/ant, not sure where it would go on Windows or Mac). (Update: I didn't have to do that with NetBeans 16 installed and launching the commands from NetBeans directly.)

from #23. I can't do it. Thank you.

**Comment by ursjoss** [comment]
@RadekCap Thanks for the PR. I have removed the paragraph from the discussion here as well.
