### ISSUE TITLE
Add a license for tr-pc repo

### ISSUE THREAD

**Issue by degrown** [thinkingrock-gtd/tr-pc#4]
Until now, this repo doesn't have a specific license attached.
As agreed with @jeremy-moore , we'll go with GPL v3: https://choosealicense.com/licenses/gpl-3.0/
At this link there's the way to add it:
- copy the license text
- paste it into a file, in the repository root, named LICENSE, or LICENSE.md or COPYING (I think LICENSE could be the safe option here)

**Comment by degrown** [comment]
I'was making a quick browsing on source files, and it seems to me that there already is a license added on every java file.
I see that, on top of every java file, there's this comment:

`*
 * The contents of this file are subject to the terms of the Common Development
 * and Distribution License (the License). You may not use this file except in
 * compliance with the License.
 *
 * You can get a copy of the License at http://www.thinkingrock.com.au/cddl.html
 * or http://www.thinkingrock.com.au/cddl.txt.
 *
 * When distributing Covered Code, include this CDDL Header Notice in each file
 * and include the License file at http://www.thinkingrock.com.au/cddl.txt.
 * If applicable, add the following below the CDDL Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyright [year] [name of copyright owner]"
 *
 * The Original Software is ThinkingRock. The Initial Developer of the Original
 * Software is Avente Pty Ltd, Australia.
 *
 * Portions Copyright 2006-2007 Avente Pty Ltd. All Rights Reserved.
 */`


There's also a folder distribution/updates/tr-updates/licenses , that maybe contains the user licenses viewed on updates.

How you'd like to manage this license change?
Maybe we can delete all these headers, and retain only a central license file?

**Comment by ursjoss** [comment]
Hi @jeremy-moore and @degrown

Thanks for the PR, @degrown. My thoughts on whether to add a license related text to each source file:

The [FAQ](https://www.gnu.org/licenses/gpl-faq.en.htm) states [here](https://www.gnu.org/licenses/gpl-faq.en.html#LicenseCopyOnly) that the license file should be in the project (and has to be shipped with each copy of the program) and states that the README should contain a comment what files are licensed under the chosen license (simply putting the license file into the repo is not clear enough).

The same paragraph (as well as [this one](https://www.gnu.org/licenses/gpl-faq.en.html#NoticeInSourceFile)) strongly recommends to put a license notice on top of each source file.

The rationale is that it is otherwise easy for the code and the license to be separated. I agree, if somebody carelessly copies source code and does not care to actively delete the license notices in the copies, there is a slight benefit of having that license notice. On the other hand:
- it would be easy for the copy-cat to simply delete those headers, nothing prevents them from doing that. (so it's a small benefit)
- Having the license notice is also a maintenance burden: Either there is a CI action that automatically rejects pull requests without the notice or somebody has to check that during pull request reviews. What if the notice is there but not the correct text - or maybe not with the correct formatting.

I believe the project would be better off avoiding the license notice in each source file.

However, the readme should clearly state for which files the license applies for (e.g. "The license applies for all source files that do not already contain a license notice." - beware, I'm neither a lawyer nor an english native speaker :-)). That would also allow to keep the license header for third party files.

What's your opinion

**Comment by ursjoss** [comment]
And, @degrown, if the decision will be to remove the license headers, I can help removing them in your PR, so you don't have to do the monkey work twice ;-)

**Comment by degrown** [comment]
Hi @ursjoss!

I've put the header license on top of all files after having read the same GNU sentences.
But thinking twice about this matter, I think you're right about that:
 
>     * Having the license notice is also a maintenance burden: Either there is a CI action that automatically rejects pull requests without the notice or somebody has to check that during pull request reviews. What if the notice is there but not the correct text - or maybe not with the correct formatting.
> 
> 
> I believe the project would be better off avoiding the license notice in each source file.

This is the main consideration: if we'll maintain all the headers, they must be checked manually, and no-one will ever read or check the license text. Garbage in, garbage out.
So, I also think that would be better to mantain only a central file BUT also (as you write):

> However, the readme should clearly state for which files the license applies for (e.g. "The license applies for all source files that do not already contain a license notice." - beware, I'm neither a lawyer nor an english native speaker :-)). That would also allow to keep the license header for third party files.
> 
> What's your opinion?

I think we could specify "all source files except otherwise noted", or something like this
(uhm but perhaps there will be images and other items...we'll have to check)

So +1 from me
Thanks

**Comment by degrown** [comment]
> And, @degrown, if the decision will be to remove the license headers, I can help removing them in your PR, so you don't have to do the monkey work twice ;-)

Thanks I'd appreciate your help very much, this will ease this task..
I think that removing will be easier than adding (I've added different license text, because they had different previous copyright years from Avente).

I think we can wait other thoughts before proceeding (like @jeremy-moore ), but I'm all for it
Thanks again

**Comment by ursjoss** [comment]
Ok, let's tackle that together when - and if - the decision about removing the license notices is final.

Another maintenance burden that just came to my mind is the update of the year in the license comment. Typically, every year, this should be amended.

Of course there are band-aids that help minimize the burden of such chore tasks (git pre-commit hooks, IDE features, plugins like the license-maven-plugin (or the gradle equivalent). But IMHO it's preferable to avoid needing to use that completely...

**Comment by degrown** [comment]
You're right, nothing beats simplicity (as I always say: what doesn't exists, doesn't break).
We'll have to chose few "moving parts" as possible, in order to lower the maintenance task.

**Comment by dougglenn** [comment]
> Hi @ursjoss
> 
> I've put the header license on top of all files after having read the same GNU sentences. But thinking twice about this matter, I think you're right about that:
> 
> > ```
> > * Having the license notice is also a maintenance burden: Either there is a CI action that automatically rejects pull requests without the notice or somebody has to check that during pull request reviews. What if the notice is there but not the correct text - or maybe not with the correct formatting.

Re: Interpretation of a Software Copyright in US was made in early or mid 2000's as a result of a couple insane claims by commercial database companies that the database copyright also included the data entered into their database. This grab resulted in a lawsuit that resulted in a ruling defining how to apply copyright and define the the data contained belongs to the company that entered it. (Since it was so long ago, it's damned difficult to look it up now. I had followed the case and knew the result and copied the ruling at the  time but it I didn't make a copy for the house. Our company updated the copyright files to our internal code. 

A rough plain language interpretation is:
1.  Reverse engineering was legal, with the exception of direct copying and insertion of a code fragment into the code in any other projects. 
2. The program must have a copyright header in the compiled source code (suggestion is placing it in a tab in the menu as the most robust means.
3. The source code must contain a copyright notice on the first line with the license it uses.
4. If the program is removed, remaining files can be reverse engineered as well. Inserting a copyright notice file at the top of the data will cover the directories in the tree below it.

The griping argument:
All the griping about the task being too onerous to update all the imports is Bu__Sh_t.  It's obvious those people can't think outside the box to figure out the simplest method to input  the copyright notice once and for all. Keyword from the ruling is 'the copyright has to be referenced.'

The solution they are missing is so simple:
The code declarations in these files only need to reference the packages License file location, if  missing from package, then a static URL location to the project website as a second means of verifying and referencing the copyright. These statements are the simplest way to eliminate updating every file, and will reference the latest Copyright notice without touching the imports again. 

In this manner,  the notice is placed the comments at the top of each file and never has to be updated again.

The only issue here is making this change since this hasn't been implemented and replaced the previous notification. This is a burden, yes. But it only needs to be done once.

Two lines is all it takes.
Copyright (Original company name), (version) released as Open Source (date) located at repository (name) 
License reference  to home directory and URL to license.

I'm no lawyer, so I'd hope the programmers here may have better idea how the wording might look like.

Be lazier

**Comment by ursjoss** [comment]
@dougglenn Thanks for your investigation and your rationale.

I realized that my experience (of not caring to put the license notices into each source file) is with BSD-3 and MIT licenses, where this practice apparently is not common.

For GPL-3, it may be on the safe side to include something - still not sure if it really makes sense, but I'm with you. Not referencing the current year (only the inception year) leaves the license notice stable for existing files, which is a good thing.

One initiative that tries to standardize such license related things is [SPDX](https://spdx.dev). Why not adhere to the conventions established in that context and also add the [SPDX ID](https://spdx.dev/ids/), to ease machine readability of the license notice.

BTW: What do we mean with GPL-3.0? Is it 
- [GPL-3.0-only](https://spdx.org/licenses/GPL-3.0-only.html) or
- [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html)

Anyway, it would still be nice to use some automation to a) set the headers and b) enforce them if the project wants to have them. With gradle as a build system, the [license-gradle-plugin](https://github.com/hierynomus/license-gradle-plugin) can both add the license notice or preamble to source files or - optionally - enforce that all files do have the proper preamble. Not sure if there is such a thing with ant, but that's also something that could be leveraged later.

**Comment by degrown** [comment]
> For GPL-3, it may be on the safe side to include something - still not sure if it really makes sense, but I'm with you. Not referencing the current year (only the inception year) leaves the license notice stable for existing files, which is a good thing.

Hi,
I think that staying on the safe side ("let's be all we can to assure our copyright") or on the easy side ("let's put a file and we're ok") it's a choice driven only by:
- the present owners
- our consensus

In my case I was initially towards the "safe side" (as you can see in the PR), but I think we can also begin with an easier way, if needed. For me the most important thing is to put a license we approve, in a acceptable way, the sooner the better, but quickly.
Then, when we have put into the repository even only a valid license file, we can think about doing a near-perfect job, with the current license (or begin to a lenghty discussion about the perfect license for this project).
But I know, to reach a decision we have to wait @clairelema and @jeremy-moore.


> The solution they are missing is so simple:
> The code declarations in these files only need to reference the packages License file location, if missing from package, then a static URL location to the project website as a second means of verifying and referencing the copyright. These statements are the simplest way to eliminate updating every file, and will reference the latest Copyright notice without touching the imports again.

My proposals are:
- @jeremy-moore has already approved (via email and via the PR) the choice of GPL-3. So, we have to be progmatic, if Jeremy or Claire will not answer about this in next days/weeks (or whatever we agree on), I think that we have to put GPL v3 and then continue to discuss about changing the license or writing the same license in another way
- i'm full with @ursjoss about doing the license changes only via automation (but I'm lost in the Java world, I can't help you); but I strongly believe that we don't have to invent a custom way to express license only to be more ergonomic. So I don't want a solution like "ok I will put a single line here with a pointer to this thing", if this is a practical solution BUT we have invented it ourselves or most of people outside is doing otherwise. Going alone will be complex, risky, tedious, error-prone.

> BTW: What do we mean with GPL-3.0? Is it
> 
>     GPL-3.0-only or
>     GPL-3.0-or-later

I think the latter is more desirable, see also http://www.gnu.org/licenses/gpl-faq.html#VersionThreeOrLater
But if someone has more hints, I'm all ears (it also seems to me that 3.0-or-later is more widely used)

Bye

**Comment by dougglenn** [comment]
I think both @degrown and @ursjoss have valid points.
re: GPL-3, is just placeholder and not a definitive selection.  I'm not up to date with v3 other than it exists. 

I would be surprised if github doesn't have a tool in its toolbox that would handle it.

I think taking a look at the copyright on the linux ethernet module during boot shows the original copyright holder and

**Comment by dougglenn** [comment]
@degrown 

I can't add myself to watchers and can only see and access the discussions from your original links in the email. 

I've got so many bookmarks that they would get lost and they don't fit the categories on my toolbar to add to.

**Comment by degrown** [comment]
Hi @dougglenn, this is really strange, these are the watchers for this repo: https://github.com/thinkingrock-gtd/tr-pc/watchers
Don't you see a "watch" rectangle above right? Click on it
This repository is public, so every GitHub user can watch and star it

**Comment by TRGTD** [comment]
Jeremy and I are fine with GPL-3.

**Comment by dougglenn** [comment]
@ursjoss @degrown 
My two cent on the copyright notice.

Here is what is shown for Donald Becker who wrote the original Ethernet code for Linux.
Written 1993-2000 by Donald Becker.
Copyright 1994-2000 by Donald Becker.

Here it could be something like your earlier comment:

My two cent on the copyright notice.

Here is what is shown for Donald Becker who wrote the original Ethernet code for Linux.
Written 1993-2000 by Donald Becker.
Copyright 1994-2000 by Donald Becker.

Here it could be something like your earlier comment:

>For example, if we saw "Copyright (C) 2006-2007 Avente Pty Ltd" we know that:
>in these years, this file was copyrighted and was of Avente Ltd
>after 2007, is not copyrighted at all (so free to use/redistribute)
>Now we have "Copyright (C) 2006 Avente Pty Ltd" it means:
>from 2006 onward, the copyright is by Avente Ltd

"Copyright (C) 2006 Avente Pty Ltd, released by Avente Pty Ltd as GPL-3 month/day/2021"

Or something like that. With perhaps a maintainer name (github) underneath as the project name? or a group name of the people who have direct access to the source code.

**Comment by dougglenn** [comment]
@degrown 
The watch is visible. I'm a newb to Github features. I suppose it would be helpful to use the 'Help' button :-)
