### ISSUE TITLE
Edit functions don't work

### ISSUE THREAD

**Issue by RadekCap** [thinkingrock-gtd/tr-pc#45]
The Edit menu is grayed all the time and keyboard binding doesn't work for Copy/Paste/Cut/Delete.

**Comment by ursjoss** [comment]
Confirmed on linux too.

But also on the official 3.7.0 I see the same:
![image](https://user-images.githubusercontent.com/357238/209436430-4837686f-0b06-47d6-adf9-3a96c3b8c72a.png)

I never used that menu - how should it behave?

**Comment by RadekCap** [comment]
Standard copy, paste etc. from clipboard. I haven't use the menu but the shortcuts.

**Comment by RadekCap** [comment]
Edit menu is probably context sensitive. And, it's working in the latest version. Currently isn't possible to paste text from the clipboard. For me is a blocker.

**Comment by RadekCap** [comment]
This is probably the issue - https://github.com/thinkingrock-gtd/tr-pc/pull/36/files

**Comment by RadekCap** [comment]
Yes, that's the issue. @ursjoss can you see in history why this was commented out? I have a strange feeling that it kick us sometime later. But now it's solving editing issue, at least for me. I'll send PR soon.
