### ISSUE TITLE
Ensure the development version is running properly on java 8

### ISSUE THREAD

**Issue by RadekCap** [thinkingrock-gtd/tr-pc#70]
By running application on MacOS with java 8 the UI is completely broken.

Ensure that the application is running at least on the LTS java versions (8, 11, 17).

**Comment by ursjoss** [comment]
Current status:

- officially released version from Avente 3.7.0 runs with java 1.8 max.
- development version (currently still 3.7.0, we should change that) min java 11.

**Comment by RadekCap** [comment]
Well, we should either check supported version during the application startup and close it when it's running on lower than 11 or implement #56 . I would say that implementation of #56 is a better solution, wdyt?

**Comment by RadekCap** [comment]
Are we going to support upgrade?

Imho the list of possible combinations of jvm/os will have tents of items. At least. I would say that it'll be nearly impossible to test and support of all combinations.

The decision has been made and the solution seems to be pack supported version into the application. After upgrading the version number there won't be any interference in between the applications.

The achievable target is not to influence existing installation of TR 3.7.
We are going to do in #56 and #33. They must to be done before we release a new version.

**Comment by ursjoss** [comment]
I suggest to close this ticket as "won't do". Currently, we have set the java source code to Java 17 and compile (target) to Java 11. So we'd not support Java 1.8 or before.
