### ISSUE TITLE
Standard keyboards shortcut conflicts

### ISSUE THREAD

**Issue by degrown** [thinkingrock-gtd/tr-pc#72]
It seems that, with the new Netbeans version, we gained also other default shortcuts, that often collides to the standard TR shortcuts.
The result is that the shortcut guided by muscle memory aren't working anymore.
(in this image: "Overview" is TR standard (is the starting page), now we have also "Open project"

<img width="759" alt="image" src="https://user-images.githubusercontent.com/91336981/214013661-85ca0d2c-c1a8-451e-91d8-2d852f8845b3.png">

I think we must remove all clashes with predefined TR shortcuts.

**Comment by RadekCap** [comment]
Hmmm, on my dev version I have only Overview, not Open project mapped to this shortcut.

![Screenshot 2023-01-23 at 18 25 33](https://user-images.githubusercontent.com/6508800/214107588-af6e7726-ad1a-4526-b94d-89ce36b187ff.png)
