### ISSUE TITLE
NetBeans preferences in TR preferences panel

### ISSUE THREAD

**Issue by degrown** [thinkingrock-gtd/tr-pc#95]
Hi, with 4.0.0 beta1, opening Preferences -> Appearance, I see a panel about FlatLaf, and this wasn't present on 3.7.
Does it belong only to the platform? Otherwise, we need to explain what the user is seeing here..

<img width="629" alt="image" src="https://user-images.githubusercontent.com/91336981/218852658-480ac6b6-dced-45ad-b8fe-850ed9188e56.png">

**Comment by ursjoss** [comment]
Yes, this should be removed. Looks like a leftover we missed in #31

**Comment by ursjoss** [comment]
That's gone now, I think we can close this ticket.
