### ISSUE TITLE
Help window doesn't open anymore

### ISSUE THREAD

**Issue by degrown** [thinkingrock-gtd/tr-pc#96]
Hi all,
on 4.0.0 beta 1 (macOS Ventura 13.2), executing TR with the command line (/trgtd/bin/trgtd, because the installer don't work anymore for me), the help panel doesn't open anymore.
The way I tried were:
- clicking F1
- clicking on menu Contextual Help
<img width="403" alt="image" src="https://user-images.githubusercontent.com/91336981/218853391-4c843299-ef30-457c-86a1-f0c92ab7d8d1.png">
- clicking on the help button
<img width="185" alt="image" src="https://user-images.githubusercontent.com/91336981/218853568-c0929f0c-9d2b-4742-8709-44c0fad40f4e.png">

no message in the console, or on standard output (is there any other place where I have to look?)

**Comment by ursjoss** [comment]
Duplicate of #37
