### ISSUE TITLE
java.lang.NoClassDefFoundError: org/hamcrest/SelfDescribing

### ISSUE THREAD

**Issue by RadekCap** [thinkingrock-gtd/tr-pc#98]
It looks like we broke dependencies in some of the previous updates.

When you build a code from the repo and run tests there are missing tests dependencies:

` [junit] Testcase: initializationError(au.com.trgtd.tr.extract.FormatTypeCsvEscapeTest):	Caused an ERROR
    [junit] org/hamcrest/SelfDescribing
    [junit] java.lang.NoClassDefFoundError: org/hamcrest/SelfDescribing
    [junit] 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
    [junit] 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
    [junit] 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
    [junit] 	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
    [junit] 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
    [junit] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
    [junit] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
    [junit] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
    [junit] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    [junit] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    [junit] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
    [junit] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    [junit] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
    [junit] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
    [junit] Caused by: java.lang.ClassNotFoundException: org.hamcrest.SelfDescribing
    [junit] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
    [junit] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
    [junit] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    [junit] 
`

According to pair debugging with @ursjoss (thanks!) we've found that there is a missing ide folder in netbeans-plat folder generated by the build.

**Comment by ursjoss** [comment]
Fixed by #100
