### ISSUE TITLE
CI do not catch netbeans platform dependency changes

### ISSUE THREAD

**Issue by RadekCap** [thinkingrock-gtd/tr-pc#99]
In our CI we are using cache. It works well but it doesn't catch issues like #98 

Consider an update or another improvement that would detect it. Ideally in the borders, we won't hit some limitations of the free GitHub repository.

**Comment by ursjoss** [comment]
The cache will have to be discarded if file `nbproject/platform.properties` has changed.

**Comment by ursjoss** [comment]
The fix is reverting the PR from #57, which I consequently had to re-open.

We need to take a second look at how to resolve that ticket w/o the regression.
